CREATE DATABASE TRAVELAPP;
USE TRAVELAPP;

CREATE TABLE USERS(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR (255) NOT NULL DEFAULT("ANONYM"),
    EMAIL VARCHAR (255) UNIQUE NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB;

SHOW TABLES;

DESCRIBE USERS;

INSERT INTO USERS(USERNAME, EMAIL, PASSWORD) VALUES ('AFAUZI', 'AKHMADFAUZI@GMAIL.COM', 'ASDASDASD3');








